### ISSUE TITLE
Исправить единицы измерения времени

### ISSUE THREAD

**Issue by orangy** [sat2707/hlcupdocs#12]
На графиках где-то миллисекунды, где-то микросекунды. Необходимо привести всё к миллисекундам.

**Comment by kswaldemar** [comment]
Или просто обозначить микросекунды как μs, чтобы не было путаницы

**Comment by orangy** [comment]
Путаница всё равно будет, такая точность (пока) не нужна. Единицы измерения должны быть одинаковые.
