### ISSUE TITLE
Keep-alive и http pipelines

### ISSUE THREAD

**Issue by orangy** [sat2707/hlcupdocs#3]
Отсутствие keep-alive и pipelining запросов приводит к тому, что системы заточенные на асинхронную обработку запросов проигрывают. Современный веб всё равно почти весь с keep-alive, а поддержать это корректно в "велосипедном" решении не просто. Более реалистичные условия выполнения тестов выровняют шансы. Туда же относится выставление content-type, accept и прочих headers, а так же проверка корректной обработки решением этих нюансов.

**Comment by cdump** [comment]
+++
kee-alive необходим!

**Comment by rayrapetyan** [comment]
up!

**Comment by sat2707** [comment]
keep-alive ввели
pipelining -- к сожалению, не будем, возможно в следующих чемпионатах
