### ISSUE TITLE
Описать логику сравнения возраста

### ISSUE THREAD

**Issue by cdump** [sat2707/hlcupdocs#32]
Я понял так;

Алгоритм преобразования возраста в timestamp:
1. Взять current unix timestamp
2. Преобразовать его в дату в UTC
3. Сделать `seconds = minute = hours = 0`
4. Сделать `years = years - age`
5. Преобразовать в unix timestamp

Если нам пришел запрос с `fromAge=AAA&toAge=BBB`, то получаем по описанному выше алгоритму
`fromAgeTimestamp` и `toAgeTimestamp`

Для включения пользователя в выборку проверяем:
```
if (fromAgeTimestamp <= userBirthdayTimestamp && userBirthdayTimestamp <= toAgeTimestamp) {
...
}
```
Я все правильно описал?

Прошу исправить меня если я не прав и перенести верный алгоритм в документацию

**Comment by vird** [comment]
Есть подозрение, что if (fromAgeTimestamp < userBirthdayTimestamp && userBirthdayTimestamp < toAgeTimestamp) {

**Comment by ei-grad** [comment]
Просто напишите тест.

**Comment by ei-grad** [comment]
Возьмите трех пользователей с возрастом 10, 20 и 30 лет. Посчитайте для них birth_date. Посмотрите как по вашей логике будет фильтроваться fromAge=15&toAge=25.

**Comment by cdump** [comment]
Я думаю тут не нужно гадать как "правильно", а важно как сделано в тестах у организаторов :)

**Comment by vird** [comment]
*Да простят меня орги за копипасту кода.

    let mut from_birth_date : DateTime<Utc> = DateTime::from_utc(NaiveDateTime::from_timestamp(i32::min_value() as i64, 0), Utc);
    let mut to_birth_date   : DateTime<Utc> = DateTime::from_utc(NaiveDateTime::from_timestamp(1000*(i32::max_value() as i64), 0), Utc);
    if fromAge != i64::min_value() {
      to_birth_date = now.with_year(now.year() - fromAge as i32).unwrap();
    }
    if toAge != i64::max_value() {
      from_birth_date = now.with_year(now.year() - toAge as i32).unwrap();
    }
    # ...
    # тут цикл
    
      let birth_date = DateTime::from_utc(NaiveDateTime::from_timestamp(user.birth_date, 0), Utc);
      if birth_date < from_birth_date    {continue};
      if birth_date > to_birth_date      {continue};

Не прокатило. Все-равно 3 битых запроса. 
/locations/51977/avg?gender=f&toAge=51

**Comment by efgen** [comment]
Полагаю, ответ для запроса /locations/51977/avg?gender=f&toAge=51 в котором учитывается пользователь, рождённый 15.08.1966, сгенерирован организаторами до 15.08.2017

**Comment by vird** [comment]
Копипаста с чатика
![image](https://user-images.githubusercontent.com/1259866/29362341-3e4fe406-8294-11e7-8843-3727a7e116bb.png)

**Comment by vird** [comment]
Рецепт как получить 100% на проде
1. now = modification time из users_1.json
2. Зануляем h,m,s
3. toAge добавляем +1 год
4. Строгие сравнения

**Comment by sat2707** [comment]
https://github.com/sat2707/hlcupdocs/blob/master/TECHNICAL_TASK.md#3--Получение-средней-оценки-достопримечательности-locationsidavg
