### ISSUE TITLE
ENV переменная с временем прогрева

### ISSUE THREAD

**Issue by atamurius** [sat2707/hlcupdocs#33]
Нужна env переменная, доступная приложению с временем до начала обстрела, поскольку для тестовых прогонов это 30 секунд, а для рейтингового -- 3 минуты, хорошо бы знать сколько доступно времени для прогрева.

**Comment by tyamgin** [comment]
Можно проифать количество файлов в data.zip

**Comment by d3sire** [comment]
Было бы круто если бы прогрев можно было устанавливать самому. Кому-то хватает всегда 15 секунд, кому-то нужно больше. Скорость прогрева не относится к проверке highload, поэтому ограничивать ее имеет мало смысла.

**Comment by atamurius** [comment]
Ифать количество, хардкодить его и время прогрева, лучше прямо сообщить приложению к какому времени нужно быть готовым (или сколько времени на это есть).

**Comment by sat2707** [comment]
Положили в данные options.txt, первая строчка - время генерации данных, вторая - 0 для теста и 1 для рейта

**Comment by atamurius** [comment]
Это в папке `/tmp/data` ?

**Comment by sat2707** [comment]
Ага

**Comment by atamurius** [comment]
Сейчас я вижу в первой строчке `1502929802`, что если понимать как timestamp соответствует 12:30, тогда как локальное время приложения в этот момент 12:55, как это понимать?
