### ISSUE TITLE
При нажатии на боевой обстрел выводить модальное окно

### ISSUE THREAD

**Issue by vird** [sat2707/hlcupdocs#35]
Которое предупреждает пользователя, что следующий обстрел будет сильно нескоро. Он точно уверен? Точно не misclick.
ИМХО будет полезно для начинающих.

**Comment by Afinogen** [comment]
Лучше еще дополнительное подтверждение запуска в модали, чтобы исключить случайны клик/тап

**Comment by sat2707** [comment]
Добавили alert
