### ISSUE TITLE
Content-Length не совпадает с длиной Body

### ISSUE THREAD

**Issue by alehano** [sat2707/hlcupdocs#37]
При POST запросах Content-Length не совпадает с длиной Body из-за дополнительного символа переноса строки. Из-за этого сервер не может нормально работать.

**Comment by AterCattus** [comment]
Посты сейчас и так не keep-alive. Прочитали, сколько нужно для ответа, ответили, да и закрыли соединение.

**Comment by alehano** [comment]
Мой веб-сервер не дает прочитать - зависает по таймауту, если данные не совпадают.

**Comment by funny-falcon** [comment]
Так а почему закрыли? Сейчас собираются keep-alive включить. Это не заафектит?
И вообще...
