### ISSUE TITLE
ENV переменная с временем прогрева REOPEN

### ISSUE THREAD

**Issue by atamurius** [sat2707/hlcupdocs#41]
В #33 я просил предоставить приложению время старта для осуществления прогрева, но в тикете добавили время генерации тестов, которое абсолютно не соответствует задаче: оно меняется раз в сутки насколько я понимаю.
Приложению нужно знать до какого момента времени можно прогревать себя.

**Comment by sat2707** [comment]
Прошу прощения, не так поняли.
По актуальному -- но ведь вы можете взять текущее время и добавить к нему 30 секунд для тестового обстрела или 3 минуты для рейтингового?

**Comment by atamurius** [comment]
Могу, хоть это и будет не очень точно
