### ISSUE TITLE
Content-Length в POST запросах

### ISSUE THREAD

**Issue by masterdidoo** [sat2707/hlcupdocs#48]
Хотелось бы получать Content-Length для всех POST запросов.
Сейчас пустые POST идут без Content-Length и Kestrel их отбрасывает с 411, а тестер ждет 400

**Comment by masterdidoo** [comment]
пример из phase_2_post.ammo:
111 POST:/visits/<entity_id>
POST /visits/8432?query_id=54 HTTP/1.1
Host: travels.com
User-Agent: tank
Accept: */*
Connection: Close

**Comment by sat2707** [comment]
Добавили Content-Length: 0 для постов без тела
