### ISSUE TITLE
Ошибка запуска тестового обстрела (Ошибка при выполнении docker-compose up)

### ISSUE THREAD

**Issue by kak-tus** [sat2707/hlcupdocs#64]
На этапе 9 получаю
```
Ошибка при выполнении docker-compose up...
Pulling client_8440 (stor.highloadcup.ru/travels/falcon_flyera:latest)...
```

Делал около 20 попыток запуска начиная со вчерашнего дня.
Примеры запусков 16880, 16780.

**Comment by nilebox** [comment]
Та же ошибка (правда код `8409`), Docker репозиторий `stor.highloadcup.ru/travels/cat_builderi`

```
Этап: 9 Окончание обстрела 23.08.2017 08:20:33
Ошибка при выполнении docker-compose up...
Pulling client_8409 (stor.highloadcup.ru/travels/cat_builderi:latest)...
```

**Comment by kak-tus** [comment]
В телеграме вчера сказали, что что-то у них со слоями в репозитории.

**Comment by nilebox** [comment]
@kak-tus а у вас получилось решить проблему? может использовать другой базовый образ, или еще что?

**Comment by nilebox** [comment]
Мой Dockerfile сейчас выглядит так:
```
FROM centos:7

WORKDIR /root

COPY bin/linux/highloadcup /root/bin/highloadcup

EXPOSE 80

CMD /root/bin/highloadcup
```
Проблема все еще актуальна. Изначально использовал базовый образ Alpine, но результат был тот же.

**Comment by kak-tus** [comment]
@nilebox Никак.
@sat2707 сказал вчера, что сегодня посмотрит.

**Comment by rayrapetyan** [comment]
Встречал два типа этой ошибки - на их стороне (возникает спонтанно и редко) и у себя в коде (когда возникает на каждом тестовом запуске).

**Comment by kak-tus** [comment]
Для моего репозитория что-то сделали. Сегодня запушил и заработало.

**Comment by Mons** [comment]
Был образ phusion/baseimage
Перестал работать
Пересобрал полностью новый образ на centos:7
Проблема та-же (но чуть более вербозная):
``` failed to register layer: ApplyLayer exit status 1 stdout: stderr: Container ID 1326596177 cannot be mapped to a host ID```
