### ISSUE TITLE
GET метод для <entity>

### ISSUE THREAD

**Issue by nerro** [sat2707/hlcupdocs#69]
В документации (https://highloadcup.ru/media/condition/howto.html) сказано, что

> Пример ответа на запрос: GET: /users/
> HTTP Status Code: 404

Разве сервер не должен отдавать все данные конкретной сущности? Сравнить хотя бы с GitHub API (https://developer.github.com/v3/issues/#list-issues)

**Comment by AterCattus** [comment]
В нашем случае нет.

**Comment by nerro** [comment]
:thinking: ok.
