### ISSUE TITLE
Пробел в Get-запросах: + или _ или %20

### ISSUE THREAD

**Issue by rekzi** [sat2707/hlcupdocs#81]
![screenshot from 2017-08-26 09-30-30](https://user-images.githubusercontent.com/2022353/29739238-9012e310-8a41-11e7-9662-ff18a673b5ce.png)

**Comment by cdump** [comment]
А в чем вопрос? И `+` и `%20` нужно понимать как пробел в query string'e

**Comment by rekzi** [comment]
@cdump Столкнулся с ошибками у себя при сравнении строк с запроса и из хранилища. Может есть имена стран с символом плюса или такое кто-то проверить хочет. Зачем вот такая неоднозначность?
```javascript encodeURIComponent("A B+C") ``` -> ```"A%20B%2BC"```.

**Comment by cdump** [comment]
@rekzi в query string параметре ("GET параметры") `+` - это всегда пробел. Но `%20` - тоже пробел. Если нужен плюс - то это `%2B`.

Это всегда так, а не только в этом конкурсе :)

**Comment by rekzi** [comment]
Я полагал нужна всего лишь перекодировка %xx. JS еще больше ввел в заблуждение.
