### ISSUE TITLE
Глюки ятанка (теперь и не в начальный момент времени)

### ISSUE THREAD

**Issue by DragoonXen** [sat2707/hlcupdocs#83]
![image](https://user-images.githubusercontent.com/1372016/29745321-295cc6c0-8ac0-11e7-9589-7d9d693a52be.png)
https://highloadcup.ru/solution/25051/#result

Что видно на графике - 3 секунды(!!!!) танк занимался ерундой и ничего не делал. Затем видимо "догнал" рпс.

В таблице про время записи за 117 сек вместо 120. Таймаутов НЕ БЫЛО!

**Comment by dbf256** [comment]
https://highloadcup.ru/solution/24160/#result - 120 записей на 3-й фазе
https://highloadcup.ru/solution/25088/#result - 119 записей на 3-й фазе

**Comment by rayrapetyan** [comment]
У меня в одном обстреле 1 пик на 750 сек, и три по ~200:
![peak1](https://user-images.githubusercontent.com/4700523/29745972-78b81956-8a6e-11e7-8536-fae9e5f66fbc.png)

В другом (тот же бинарник) - пик на 750 ушел, осталось 3 по ~200:
![peak2](https://user-images.githubusercontent.com/4700523/29745983-decff088-8a6e-11e7-9fe9-55bb0a50df58.png)

Расцениваю это как глюки танка. Чем такое можно вылечить?

**Comment by DragoonXen** [comment]
Последний график очень похож на мой. Вначале очевидный косяк танка, дальше же два пика, где косяк танка недоказуем, глядя только на график (но уверен, что это его косяк).

**Comment by cdump** [comment]
У меня в последнем обстреле тоже пики вылезли, в чатике было интересное предположение:

> Есть предположение, что танк пишет свои логи на диск и это момент сброса накопившихся dirty буферов. @sat2707 - такое возможно?

Локально гоняю танком с боевымы данными и боевым профилем 3ю фазу, за все разы ни одного пика не увидел.

**Comment by ewgRa** [comment]
Еще есть мысль что эти пики связаны с выделением/освобождением памяти на уровне ОС.

Связанное с memlock (https://github.com/sat2707/hlcupdocs/issues/67), ну или возможно когда приложение просто памяти у ОС запрашивает, даже не не уровне докера.

**Comment by AterCattus** [comment]
Локально были замечены пики при записи на диск.
![photo5269608118810159166](https://user-images.githubusercontent.com/433484/29775348-8daec422-8c0d-11e7-9330-745329fcd306.jpg)

**Comment by rayrapetyan** [comment]
> Еще есть мысль что эти пики связаны с выделением/освобождением памяти на уровне ОС.
Исключено, у меня, например, на третьей фазе нет выделения памяти, а пики только там вылазят.

**Comment by DragoonXen** [comment]
> Исключено, у меня, например, на третьей фазе нет выделения памяти, а пики только там вылазят.

скорее не исключено, ты же не в курсе, когда и где память выделяет танк?) Тут вопрос в том, в каком месте у него тормоз

**Comment by rayrapetyan** [comment]
Просто было написано "приложение просто памяти у ОС запрашивает", а танк конечно, что угодно может запрашивать в данной ситуации...

**Comment by ewgRa** [comment]
@rayrapetyan на новые entity или на обновление да, но на коннекты и их обработку совсем-совсем никто за памятью не ходит?

**Comment by rayrapetyan** [comment]
Разве что в ядре. У аппликухи своя нерасширяемая куча.

**Comment by sat2707** [comment]
Кажется нас спас tmpfs, в который был посажен танк с его логами

**Comment by rayrapetyan** [comment]
Потверждаю - остался только один пик на 12 сек, все крупные ушли.

**Comment by rayrapetyan** [comment]
Стало лучше, но от идеала далеко - на 48 сек пиков из 300 словил в
последнем обстреле.

**Comment by rayrapetyan** [comment]
Все же предлагаю резать пики в финальном обстреле у всех хотя бы по stdev*10
