### ISSUE TITLE
Killed рейтинговый запуск

### ISSUE THREAD

**Issue by ewgRa** [sat2707/hlcupdocs#84]
"Решение id=25166"

Падает при попытке загрузить в память данные о юзерах. Читал в комите что это "скорее всего" связано с тем что решение вышло за границы памяти.

Полностью загруженное тестовое решение занимает в памяти 300mb, я сильно сомневаюсь что рейтинговое решение (x10) при попытке загрузить юзеров в память (самая первая операция) 
 вылазит за органичения.

1. Зря имхо вы под завершение чемпионата так кардинально поменяли тестовые данные. Это было странное решение, вместо того чтобы сосредоточиться в финальной части на улучшении решения, теперь приходиться воевать с черной кошкой в темной комнате.

2. Можете рассказать что стоит за killed? Как происходит проверка которая решает kill делать? Какие-нибудь технические подробности хотя бы.

**Comment by cdump** [comment]
> Полностью загруженное тестовое решение занимает в памяти 300mb

Ты можешь проверить на полных данных, они в этой репе есть, наверняка все же вылазишь за 4гб.

**Comment by ewgRa** [comment]
@cdump для всех данных наверняка, но не для юзеров точно, они первые загружаются. буду ковырять конечно, куда деваться
