### ISSUE TITLE
Обязательные заголовки

### ISSUE THREAD

**Issue by mtrempoltsev** [sat2707/hlcupdocs#86]
С такими заголовками все ответы проходят:

```
HTTP/1.1 200 OK\r\n
Server: mt1\r\n
Connection: close\r\n
Content-Type: application/json\r\n
Content-Length: 2\r\n
\r\n
```

Если убрать, например, целиком строку с Server, то будет ошибка:

> 
{} doesn't have one of required headers: Status-Line, Server, Connection, Content-Length

Странно, что без части заголовков у некоторых все работает:

> Очень странно. Тестовый обстрел у меня не работает без Connection и Content-Type.

> А я никогда не отдаю Connection ._.

> никогда не отдавал Server

> отдаю только Connection и Content-Length и все ок

И т.д. Прошу разобраться почему условия для разных участников разные.

**Comment by sat2707** [comment]
По ТЗ мы ждем: Status-Line, Server, Connection, Content-Length.
Действительно, там была нестрогая проверка. В финале будет строгая. Я бы советовал отдавать заголовки по ТЗ

**Comment by sat2707** [comment]
Приносим извинения за дезинформацию. Сейчас проверяется лишь количество заголовков, и править эту ошибку за 3 дня до финала мы не будем.
