### ISSUE TITLE
Нужны ли проверки на корректность дат(birth_date, visited_at)?

### ISSUE THREAD

**Issue by Frank591** [sat2707/hlcupdocs#87]
В первой версии задания были ограничения на диапазон дат по полям birth_date, visited_at, однако
в текущей версии тех. задания ничего такого не сказано. Просьба уточнить и добавить в описание тех. задания эту информацию.

**Comment by rekzi** [comment]
Эти ограничения убрали, нечего добавлять.

**Comment by sat2707** [comment]
Да, мы действительно убрали эти ограничения

**Comment by Frank591** [comment]
на будущее - неплохо бы сообщать о таких изменениях
