### ISSUE TITLE
Функция округления при расчёте /locations/<id>/avg

### ISSUE THREAD

**Issue by 1yura** [sat2707/hlcupdocs#88]
Дайте, пожалуйста вашу эталонную функцию округления. 
С-ишный printf("%0.5f", ...); дал 4 несоответствия на рейтинговой выборке, на тех выборках что выложены в паблик - расхождений нет. Там где получал расхождения - всегда в последней цифре, что с вероятностью близкой к 1 означает, что проблема в округлении.
Либо (вы же разумные люди?), давайте всё-таки дробные числа сравнивать путём вычитания и сравнения дельты с погрешностью.

**Comment by AndrewBurdyug** [comment]
Могу ошибаться, но по-моему форматирование в принте просто отсечёт, а не округлит, 
думается, что надо в Си использовать *round* (как в и других языках программирования, она везде так и называется также или похожее название имеет), примеры из гугла: 

http://www.codecogs.com/library/computing/c/math.h/round.php
http://fresh2refresh.com/c-programming/c-arithmetic-functions/c-round-function/

**Comment by 1yura** [comment]
Форматирование в принте именно округляет, а не отсекает. Спасибо за наводку, сейчас попробую.

**Comment by 1yura** [comment]
>"Использую пайтоновский round ни разу не было несоответствий в обстрелах"
С C-ишным round тоже несоответствия ушли, спасибо. Тему прикрою, но организаторам - это всё-таки дикость, так сравнивать дробные числа.
