### ISSUE TITLE
Странный рейтинг решения

### ISSUE THREAD

**Issue by ewgRa** [sat2707/hlcupdocs#89]
Решение id=30151, (102006.997944) 

Практически идентичное решение получило (Решение id=28845) 264.

По ответам разница в 8 неверных ответов, по скорости плюс-минус идентичны.

Сильно большая разница какая-то... можно пояснения?

**Comment by sat2707** [comment]
К сожалению, ночью была ошибка в данных, из-за которой часть решений незаслуженно получили ошибки out of bounds, сейчас все они перезапущены. Естественно, КД на рейтинговый запуск не сдвинется, т.к. время сабмита мы не меняли и они перезапущены "в прошлом"
